
exports.seed = function (knex, Promise) {
  // Deletes ALL existing entries
  return knex('adventures').del()
    .then(function () {
      // Inserts seed entries
      return knex('adventures').insert([
        {
          adv_id: 1, adv_name: 'Escape the Tomb', flav_text: '"Heroes, alone in the dungeon crypts, must escape before the sun sets and Strahd returns...“', Goal: 'Find the Secret Stairway tile that leads out of the dungeon before Strahd defeats you!', spec_components: 'Strahd’s Crypt Dungeon Tile, Secret Stairway Dungeon Tile, Sun token, Strahd Villain Card, Strahd figure.', adv_setup: 'Place the Strahd’s Crypt tile on the table. Place the Hero on any square on the tile.', adv_rules: 'game_assets/adv_start_tiles/1.js', victory: 'You win the game when a Hero starts his or her turn on the Secret Stairway tile.', defeat: 'The Hero loses this adventure if he or she has 0 Hit Points at the start of his or her turn and there are no Healing Surge tokens remaining.', start_adv: 'You wake up alone in the depths of Castle Ravenloft. The last thing you remember was the man with the piercing eyes and long cape approached you on the dark street outside the inn. It had to be Count Strahd, the vampire! Outside the castle, you know that the sun is high in the sky. Now you have to find your way out of here before the sun sets and Strahd returns to finish whatever foul plot he began last night.', adv_reveal: 'Now the sun sets...Somewhere in the darkness behind you, you hear the sound of stone scrapping on stone.It must be the sound of Strahd’s coffin lid sliding open.The vampire lord has awakened...',
        },
        {
          adv_id: 2, adv_name: 'Find the Icon of Ravenloft ', flav_text: 'The Heroes must enter the depths of Castle Ravenloft and locate the one chamber untouched by the evil of the place—the Chapel.There, the Icon of Ravenloft waits to help end Strahd’s evil.', Goal: 'Find the hidden Chapel and recover the lost Icon of  Ravenloft.', spec_components: 'Start Dungeon Tile, two Hallway Dungeon Tiles, Chapel Dungeon Tile, Icon of Ravenloft Treasure Card, Icon of Ravenloft token.', adv_setup: 'Place the Start tile on the table. Place the two Hallway tiles adjacent to the Start tile. Place each Hero on a square adjacent to the stairway on the Start tile.', adv_rules: 'game_assets/adv_start_tiles/2.js', victory: 'The Heroes win this adventure when they destroy all of the Monsters placed on the Chapel and recover the Icon of Ravenloft.', defeat: 'The Heroes lose this adventure if any Hero has 0 Hit Points at the start of his or her turn and there are no Healing Surge tokens remaining.', start_adv: ' A cleric in Barovia has told you about the legend of the Icon of Ravenloft. He believes the artifact still exists, resting in the hidden Chapel deep within the castle.“The Chapel remains a safe haven, a place of goodness and light in all that terrible darkness the cleric explained.“If you can bring the icon Lo me.I can use it to defend the town from Strahd and his minions—and perhaps even find a way to destroy the vampire lord once and for all!” Now you stand at the bottom of the stairs leading into the dungeon crypts. The only thing between you and your goal—endless corridors of darkness and an army of of monsters!', adv_reveal: "The chamber ahead glows with the light of faith and goodness. On the pristine altar, an ancient platinum medallion shaped like the sun with a large crystal embedded in its center waits to be collected. Unfortunately, the chamber isn't empty.Some monsters stand guard, as though they were waiting for you to arrive.",
        },
        {
          adv_id: 3, adv_name: 'Klak’s Infernal Artifact', flav_text: 'The Heroes must enter the dungeon crypts and discover the source of the chaos magic that has suddenly begun to torment the land.', Goal: 'Defeat Klak and destroy the infernal artifact.', spec_components: 'Start Dungeon Tile, Laboratory Dungeon Tile, Klak Villain Card, Klak figure, Klak’s Artifact token.', adv_setup: 'Each player shuffles the Power Cards he or she isn’t using and puts them face down on the table, creating a Power Card deck for later use.', adv_rules: 'game_assets/adv_start_tiles/3.js', victory: 'The Heroes win the adventure by defeating Klak and destroying his artifact.', defeat: 'The Heroes lose this adventure if any Hero has 0 Hit Points at the start of his or her turn and there are no Healing Surge tokens remaining.', start_adv: 'In recent days, storms of chaotic magic have swirled out of Castle Ravenloft and wreaked havoc throughout the land of Barovia. The town’s council of elders has asked you to enter the castle, discover the cause of this deadly magic, and put a stop to the periodic storms before all of Barovia is destroyed.', adv_reveal: "The chamber ahead appears to be a magic-user’s laboratory, although it appears that the practitioner working here indulges in dark magic.You see a kobold in sorcerer's robes. He is in the mids of casting a ritual over a strange artifact. 'Klak is busy!' the kobold sorcerer shouts when he notices you. “I must finish my work before Master Strahd becomes angry. Go away!“ As you watch, a wave of chaotic energy radiates from the artifact and swirls upward, toward Barovia. 'Soon,' Klak says, 'my infernal artifact will be ready to cast its spell and destroy Barovia! Hahaha!'",
        },
        {
          adv_id: 4, adv_name: 'Daylight Assault', flav_text: 'The Heroes enter the dungeon crypts early in the morning to steal Strahd’s treasures while he sleeps.', Goal: 'Collect 12 Treasure Cards and escape from the dungeon with them.', spec_components: 'Start Dungeon Tile, Sun token.', adv_setup: 'Place the Start tile on the table. Place each Hero on a square adjacent to the stairway on the Start tile. Shuffle the Dungeon Tile stack.There is no special Dungeon Tile for this adventure.', adv_rules: 'game_assets/ adv_start_tiles / 4.js', victory: 'The Heroes win the adventure when any number of Heroes escapes the dungeon with a total of 12 Treasure Cards. (One Hero can end his or her turn on the Start tile with all 12 cards, for example, or three Heroes can carry 4 cards each to attain victory.)', defeat: 'The Heroes lose this adventure if any Hero has 0 Hit Points at the start of his or her turn and there are no Healing Surge tokens remaining.', start_adv: 'You have come up with a daring plan: Enter Castle Ravenloft during the day, while che vampire lord Strahd sleeps, and steal as many magic items as you can.Of course, not all of the monsters guarding the castle rest during the day...', adv_reveal: 'The castle suddenly seems to awaken, and you can hear a multitude of foul creatures stirring in the darkness all around you.',
        },
        {
          adv_id: 5, adv_name: 'The Final Transformation', flav_text: 'The Heroes must help a young villager named Kavan. Strahd has begun the process of transforming Kavan into a vampire, and the only way to save him is to enter Castle Ravenloft.', Goal: 'Explore Castle Ravenloft to locate a magic fountain whose dark waters can reverse the magic transforming young Kavan into a vampire.', spec_components: 'Start Dungeon Tile, Dark Fountain Dungeon Tile, Kavan token, Young Vampire Villain Card, Strahd figure, 5 Hit Point tokens.', adv_setup: 'Place the Start tile on the table. Place each Hero on a square adjacent to the stairway on the Start tile. Place the Kavan token on a square adjacent to the stairway on the Start tile.', adv_rules: 'game_assets/ adv_start_tiles / 5.js', victory: '', defeat: '', start_adv: '', adv_reveal: '',
        },
        { adv_id: 6, adv_name: '', flav_text: 'rowValue3', Goal: '', spec_components: '', adv_setup: '', adv_rules: '', victory: '', defeat: '', start_adv: '', adv_reveal: '', },
        { adv_id: 7, adv_name: '', flav_text: 'rowValue1', Goal: '', spec_components: '', adv_setup: '', adv_rules: '', victory: '', defeat: '', start_adv: '', adv_reveal: '', },
        { adv_id: 8, adv_name: '', flav_text: 'rowValue2', Goal: '', spec_components: '', adv_setup: '', adv_rules: '', victory: '', defeat: '', start_adv: '', adv_reveal: '', },
        { adv_id: 9, adv_name: '', flav_text: 'rowValue3', Goal: '', spec_components: '', adv_setup: '', adv_rules: '', victory: '', defeat: '', start_adv: '', adv_reveal: '', },
        { adv_id: 10, adv_name: '', flav_text: 'rowValue1', Goal: '', spec_components: '', adv_setup: '', adv_rules: '', victory: '', defeat: '', start_adv: '', adv_reveal: '', },
        { adv_id: 11, adv_name: '', flav_text: 'rowValue3', Goal: '', spec_components: '', adv_setup: '', adv_rules: '', victory: '', defeat: '', start_adv: '', adv_reveal: '', },
        { adv_id: 12, adv_name: '', flav_text: 'rowValue2', Goal: '', spec_components: '', adv_setup: '', adv_rules: '', victory: '', defeat: '', start_adv: '', adv_reveal: '', },
        { adv_id: 13, adv_name: '', flav_text: 'rowValue2', Goal: '', spec_components: '', adv_setup: '', adv_rules: '', victory: '', defeat: '', start_adv: '', adv_reveal: '', },
      ]);
    });
};
