
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('table_name').del()
    .then(function () {
      // Inserts seed entries
      return knex('table_name').insert([
        {id: 1, character_id: 1, type:'utility power', title:'Healing Word', subtitle:'You whisper a brief prayer, and a divine healing light washes over your companion.', instruction_1:'Use this power during your Hero Phase', instruction_2:'One hero regains Hit Points equal to his or her healing surge value', attack:null, damage:null, miss:null},
        {id: 3, character_id: 1, type:'utility power', title:'Bless', subtitle:'You call forth a holy blessing for you and your companions.', instruction_1:'Use this power during your Hero Phase', instruction_2:'Each Hero within 1 tile of you gains a +2 bonus to attack rolls untill the end of your next Hero Phase', attack:null, damage:null, miss:null},
        {id: 2, character_id: 1, type:'utility power', title:'Consecrated Ground', subtitle:'You sanctify the ground around you, warding it from evil', instruction_1:'Use this power during your Hero Phase instead of attacking', instruction_2:'Choose a tile within 1 tile of you. If there is a marker on that tile, discard it. Place the Consecreated Ground marker on the chosen tile. The next time you would place an Encounter marker on that tile, discard that Encounter Card and do not draw the new Encounter Card. Then discard the Consecrated Ground marker', attack:null, damage:null, miss:null},
        {id: 4, character_id: 1, type:'utility power', title:'Shield of Faith', subtitle:'Divine energy protects you and your companions', instruction_1:'Use when you or a Hero on your tile is hit by an attack', instruction_2:'The attack misses instead. You and each Hero within 1 tile of you gains a +2 bonus to AC untill the end of your next Hero Phase', attack:null, damage:null, miss:null},
        {id: 5, character_id: 1, type:'At-Will-Power', title:'Divine Flare', subtitle:'The light of your deity scorches your foe and empowers your ally', instruction_1:'Attack one Monster on your tile', instruction_2:'If you hit, end one Condition on a Hero on your tile', attack:6, damage:1, miss:0},
        {id: 6, character_id: 1, type:'At-Will-Power', title:'Healing Strike', subtitle:'You smite your foe and heal a nearby companion', instruction_1:'Attack one adjacent Monster', instruction_2:'if you hit, choose one hero within 1 tile of you. That Hero regains 1 hit Point', attack:8, damage:1, miss:0},
        {id: 7, character_id: 1, type:'At-Will-Power', title:'Lance of Faith', subtitle:'You sear your foe with a brilliant ray of Golden radiance', instruction_1:'Attack one Monster within 1 tile of you', instruction_2:'If the Monster is Undead, you deal +1 damage with this attack', attack:6, damage:1, miss:0},
        {id: 8, character_id: 1, type:'Daily-Power', title:'Beacon of Hope', subtitle:'You blast your foes with radiant light and your allies are heartened by the attack', instruction_1:'Choose a tile within 1 tile of you. Attack each Monster on that tile', instruction_2:'Each Hero on the chosen tile regains 1 Hit point.', attack:6, damage:2, miss:0},
        {id: 9, character_id: 1, type:'Daily-Power', title:'Flame Strike', subtitle:'A column of flame engulfs your foes', instruction_1:'Choose a tile within 2 tiles of you. Attack each Monster on that tile', instruction_2:'', attack:6, damage:3, miss:1},
        {id: 10, character_id: 1, type:'Daily-Power', title:'Hallowed Advance', subtitle:'The power of your god inspires your allies to action', instruction_1:'Attack one adjacent Monster', instruction_2:'Hit or miss, each other Hero can move 1 tile', attack:5, damage:3, miss:1},
        {id: 11, character_id: 2, type:'utility power', title:'Stealth', subtitle:'Your silent advance avoids unwanted attention', instruction_1:'Usae this power immediately after you draw a Monster Card', instruction_2:'Discard the Monster Card instead of placing it', attack:null, damage:null, miss:null},
        {id: 12, character_id: 2, type:'utility power', title:'Spring Away', subtitle:' You sense trouble coming and move away before it catches you', instruction_1:'Use this power when another Hero draws an Encounter Card', instruction_2:'Place your Hero on a tile 2 tiles away from you before the Encounter Card triggers', attack:null, damage:null, miss:null},
        {id: 13, character_id: 2, type:'utility power', title:'Great Leap', subtitle:'You get a running start and leap a great distance', instruction_1:'Use this power during your Hero Phase instead of moving', instruction_2:'Place your Hero on a tile within 2 tiles of you', attack:null, damage:null, miss:null},
        {id: 14, character_id: 2, type:'utility power', title:'Sneack Attack', subtitle:'You emerge from the shadows and position yourself to deliver a powerful strike to your enemy.', instruction_1:'Use this power at the start of your Hero Phase', instruction_2:'You gain a +4 bonus to attack rolls and deal +1 damage until the end of your next Hero Phase', attack:null, damage:null, miss:null},
        {id: 15, character_id: 2, type:'At-Will-Power', title:'', subtitle:'', instruction_1:'', instruction_2:'', attack:1, damage:1, miss:1},
        {id: 16, character_id: 2, type:'At-Will-Power', title:'', subtitle:'', instruction_1:'', instruction_2:'', attack:1, damage:1, miss:1},
        {id: 17, character_id: 2, type:'At-Will-Power', title:'', subtitle:'', instruction_1:'', instruction_2:'', attack:1, damage:1, miss:1},
        {id: 18, character_id: 2, type:'Daily-Power', title:'', subtitle:'', instruction_1:'', instruction_2:'', attack:1, damage:1, miss:1},
        {id: 19, character_id: 2, type:'Daily-Power', title:'', subtitle:'', instruction_1:'', instruction_2:'', attack:1, damage:1, miss:1},
        {id: 20, character_id: 2, type:'Daily-Power', title:'', subtitle:'', instruction_1:'', instruction_2:'', attack:1, damage:1, miss:1},
        {id: 21, character_id: 3, type:'utility power', title:'', subtitle:'', instruction_1:'', instruction_2:'', attack:null, damage:null, miss:null},
        {id: 22, character_id: 3, type:'utility power', title:'', subtitle:'', instruction_1:'', instruction_2:'', attack:null, damage:null, miss:null},
        {id: 23, character_id: 3, type:'utility power', title:'', subtitle:'', instruction_1:'', instruction_2:'', attack:null, damage:null, miss:null},
        {id: 24, character_id: 3, type:'utility power', title:'', subtitle:'', instruction_1:'', instruction_2:'', attack:null, damage:null, miss:null},
        {id: 25, character_id: 3, type:'At-Will-Power', title:'', subtitle:'', instruction_1:'', instruction_2:'', attack:1, damage:1, miss:1},
        {id: 26, character_id: 3, type:'At-Will-Power', title:'', subtitle:'', instruction_1:'', instruction_2:'', attack:1, damage:1, miss:1},
        {id: 27, character_id: 3, type:'At-Will-Power', title:'', subtitle:'', instruction_1:'', instruction_2:'', attack:1, damage:1, miss:1},
        {id: 28, character_id: 3, type:'Daily-Power', title:'', subtitle:'', instruction_1:'', instruction_2:'', attack:1, damage:1, miss:1},
        {id: 29, character_id: 3, type:'Daily-Power', title:'', subtitle:'', instruction_1:'', instruction_2:'', attack:1, damage:1, miss:1},
        {id: 30, character_id: 3, type:'Daily-Power', title:'', subtitle:'', instruction_1:'', instruction_2:'', attack:1, damage:1, miss:1},
        {id: 31, character_id: 4, type:'utility power', title:'', subtitle:'', instruction_1:'', instruction_2:'', attack:null, damage:null, miss:null},
        {id: 32, character_id: 4, type:'utility power', title:'', subtitle:'', instruction_1:'', instruction_2:'', attack:null, damage:null, miss:null},
        {id: 33, character_id: 4, type:'utility power', title:'', subtitle:'', instruction_1:'', instruction_2:'', attack:null, damage:null, miss:null},
        {id: 34, character_id: 4, type:'utility power', title:'', subtitle:'', instruction_1:'', instruction_2:'', attack:null, damage:null, miss:null},
        {id: 35, character_id: 4, type:'At-Will-Power', title:'', subtitle:'', instruction_1:'', instruction_2:'', attack:1, damage:1, miss:1},
        {id: 36, character_id: 4, type:'At-Will-Power', title:'', subtitle:'', instruction_1:'', instruction_2:'', attack:1, damage:1, miss:1},
        {id: 37, character_id: 4, type:'At-Will-Power', title:'', subtitle:'', instruction_1:'', instruction_2:'', attack:1, damage:1, miss:1},
        {id: 38, character_id: 4, type:'Daily-Power', title:'', subtitle:'', instruction_1:'', instruction_2:'', attack:1, damage:1, miss:1},
        {id: 39, character_id: 4, type:'Daily-Power', title:'', subtitle:'', instruction_1:'', instruction_2:'', attack:1, damage:1, miss:1},
        {id: 40, character_id: 4, type:'Daily-Power', title:'', subtitle:'', instruction_1:'', instruction_2:'', attack:1, damage:1, miss:1},
        {id: 41, character_id: 5, type:'utility power', title:'', subtitle:'', instruction_1:'', instruction_2:'', attack:null, damage:null, miss:null},
        {id: 42, character_id: 5, type:'utility power', title:'', subtitle:'', instruction_1:'', instruction_2:'', attack:null, damage:null, miss:null},
        {id: 43, character_id: 5, type:'utility power', title:'', subtitle:'', instruction_1:'', instruction_2:'', attack:null, damage:null, miss:null},
        {id: 44, character_id: 5, type:'utility power', title:'', subtitle:'', instruction_1:'', instruction_2:'', attack:null, damage:null, miss:null},
        {id: 45, character_id: 5, type:'At-Will-Power', title:'', subtitle:'', instruction_1:'', instruction_2:'', attack:1, damage:1, miss:1},
        {id: 46, character_id: 5, type:'At-Will-Power', title:'', subtitle:'', instruction_1:'', instruction_2:'', attack:1, damage:1, miss:1},
        {id: 47, character_id: 5, type:'At-Will-Power', title:'', subtitle:'', instruction_1:'', instruction_2:'', attack:1, damage:1, miss:1},
        {id: 48, character_id: 5, type:'Daily-Power', title:'', subtitle:'', instruction_1:'', instruction_2:'', attack:1, damage:1, miss:1},
        {id: 49, character_id: 5, type:'Daily-Power', title:'', subtitle:'', instruction_1:'', instruction_2:'', attack:1, damage:1, miss:1},
        {id: 50, character_id: 5, type:'Daily-Power', title:'', subtitle:'', instruction_1:'', instruction_2:'', attack:1, damage:1, miss:1},
      ]);
    });
};
