// Encounter event types
// 0 - Event
// 1 - Event, attack
// 2 - Environment
// 3 - trap

exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('encounters').del()
    .then(function () {
      // Inserts seed entries
      return knex('encounters').insert([
        {id: 1, evt_type: 0, name: 'Voice of the master', flavour: 'Strahd\'s voice echoes through the catacombs. "Slay them, my minions!" The monsters around you surge forward to attack', description:'Starting with the hero on your left, each Hero immediately activates one Monster they control. The first Hero that cannot activate a Monster instead places a new Monster on any tile'},
        {id: 2, evt_type: 0, name: 'Passage of time', flavour: 'The unholy air in Strahd\'s crypts saps the strength from you and your companions', description:'Each Hero takes 1 damage'},
        {id: 3, evt_type: 0, name: 'Passage of time', flavour: 'The unholy air in Strahd\'s crypts saps the strength from you and your companions', description:'Each Hero takes 1 damage'},
        {id: 4, evt_type: 0, name: 'Howl of the wolf', flavour: 'The distant baying of a wolf echoes through the dungeon, causing the monsters around you to shriek in response', description:'Choose one Monster on any Hero\'s tile. That Monster immediately activates'},
        {id: 5, evt_type: 0, name: 'Neglected passage', flavour: '"Did you look down that hall?"', description:'If a Start tile is not in play, discard this card and draw a nwe Encounter Card.\nDraw a tile frm the bottom of the Dungeon Tile stack and place it adjacent to the unexplored edge that is closest to the Start tile.\nPlace a new Monster on that tile. But do not draw an Encounter Card'},
        {id: 6, evt_type: 0, name: 'Spirit of doom', flavour: 'The entire crypt shuddered as though some gargantuan creature was moving deep below', description:'Each Hero can immediately move up to his or her Sped. After this moe each Hero on a tile with no Monsters takes 1 damage'},
        {id: 7, evt_type: 0, name: 'Overwhelming terror', flavour: 'A cacophony of shrieks and howls rises up around you and flee in terror.', description:'If a start tile is not in play, discard this card and draw a new Encounter Card.\nPlace each Hero 2 tiles closer to the same tile as a Monster after being placed. That Hero is Slowed'},
        {id: 8, evt_type: 0, name: 'Corner of your eye', flavour: 'You investigate something moving in the darkness.', description:'Place the active Hero on an adjacent tile and roll the die:\n1-15: A Monster rushes you from the darkness. Place a new Monster on the active Hero\'s tile.\n16-20: A friendly spirit inspires you to fight on. Flip up one of your used powers.'},
        {id: 9, evt_type: 0, name: 'Bubbling cauldron', flavour: 'The monsters around you rush forward, drawn by a repulsive odor spilling out of a bubbling cauldron', description:'Place each Monster 1 tile closer to the active hero'},
        {id: 10, evt_type: 0, name: 'Frenzy', flavour: 'The monsters around you roar in fury.', description:'Each Monster you control activates twice during your Villain phase'},
        {id: 11, evt_type: 0, name: 'Teleport glyph', flavour: 'An arcane symbol flashes at your feat and you disappear from sight.', description:'Place the active Hero and each Monster on his or her tile on the tile farthest from the active Hero'},
        {id: 12, evt_type: 0, name: 'Prowling spirits', flavour: 'Cold, spectral hands grasp at you. Before you can react, one of your items is gone.', description:'You must discard one of your Treasure Cards (of your choice)'},
        {id: 13, evt_type: 0, name: 'Strahd\'s minions', flavour: 'Strahd steps from the shadows and casts a spell', description:'Place the active Hero and the two Monsters that are closest to that Hero on the tile farthest from the active Hero.\nIf there are less than two Monsters in play, place a new Monster adjacent to the active Hero after he or she is placed'},
        {id: 14, evt_type: 0, name: 'Strahd\'s trick', flavour: 'Your mind reels as Strahd places a spell upon you. Your friends become enemies and your enemies become friends.', description:'Place the active Hero on a tile within 1 tile of you that has the most Monsters on it. If no tile within 1 tile of you has Monsters, the active Hero takes 1 damage.'},
        {id: 15, evt_type: 0, name: 'Lief lipsiege', flavour: 'A gnarled old man dressed as a clerk steps from the shadows. "I watch the master\'s treasure, At least, I do unless I\'m distracted."', description:'You try to distract Lief, Roll a die:\n1-10: You scare Lief and he calls for help. Place a new Monster on the active Hero\'s tile.\n11-20: Draw a treasure card.'},
        {id: 16, evt_type: 0, name: 'Frenzy', flavour: 'The monsters around you roar in fury.', description:'Each Monster you control activates twice during your Villain phase'},
        {id: 17, evt_type: 0, name: 'Strahd\'s whispers', flavour: 'Strahd\'s voice echoes in your mind, compelling you to turn against your friends.', description:'Place the active Hero adjacent to the next closest Hero. The active Hero attacks that Hero with an at-will power'},
        {id: 18, evt_type: 0, name: 'Ghost of prince Aurel', flavour: 'A ghost materialises in the corridor ahead; its horrid features freeze you in terror', description:'Flip over one unused Daily power or Utility power. If you don\'t have an unused power to flip over, take 1 damage instead'},
        {id: 19, evt_type: 0, name: 'Overrun', flavour: 'Monsters charge from all directions', description:'Each Hero takes damage equal to the number of Monsters they control'},
        {id: 20, evt_type: 0, name: 'Illusionary trick', flavour: 'Even allies aren\'t always what they appear to be!', description:'The active Hero swaps positions with the Monster that is farthest from them'},
        {id: 21, evt_type: 0, name: 'Secret door', flavour: 'A section of the stone wall slides away, revealing a hidden chamber', description:'Draw a tile from the bottom of the Dungeon Tile stack and place it adjacent to the unexplored edge that is closest to the active Hero.\nPlace a new Monster on that tile. BUt do not draw an Encounter Card'},
        {id: 22, evt_type: 0, name: 'Cowardly flight', flavour: 'A monster flees from you to seek help', description:'If there are no Monsters in play, discard this card.\nDraw a tile from the bottom of the Dungeon Tile stack and place it adjacent to the unexplored edge that is closest to the active Hero. Place the eMonster closest to the active Hero on tha tile, and place a new Monster on that tile. Do not draw an Encounter Card.'},
        {id: 23, evt_type: 0, name: 'Summoning circle', flavour: 'A careless misstep disturbs a magic rune, freeing a horrid creature', description:'Place a new Monster adjacent to the active Hero'},
        {id: 24, evt_type: 0, name: 'Overrun', flavour: 'Monsters charge from all directions!', description:'Each Hero takes damage equal to the number of Monsters he or she controls'},
        {id: 25, evt_type: 0, name: 'Neglected passage', flavour: '"Did you look down that hall?"', description:'If a Start tile is not in play, discard this card and draw a nwe Encounter Card.\nDraw a tile frm the bottom of the Dungeon Tile stack and place it adjacent to the unexplored edge that is closest to the Start tile.\nPlace a new Monster on that tile. But do not draw an Encounter Card'},
        {id: 26, evt_type: 0, name: 'Strahd\'s hunger', flavour: 'Vertigo washes over you as Strahd steps form the shadows. His will overwhelms you, and he laughs as he steps bak into the darkness', description:'Choose the hero with the most Hit Points remaining. That Hero takes 1 damage and is Immobilized'},
        {id: 27, evt_type: 0, name: 'Treasure chest', flavour: 'You find an ancient chest with a rusty lock', description:'You open a treasure chest. Roll a die:\n1-10: Take 2 damage.\n11-15: Take 1 damage and draw 1 Treasure Card.\n16-20: Draw 1 Treasure Card.'},
        {id: 28, evt_type: 0, name: 'Mists of terror', flavour: 'You hear a whispering chant, and a white mist flows through the crypts. As you breathe in the foul air, horrifying thoughts root you in place.', description:'Roll a die for each Hero. On a 1-5 the Hero takes 1 damage and is Immobilized'},
        {id: 29, evt_type: 0, name: 'Reinforcements', flavour: 'The constant advance of Strahd\'s minions gives you no time to relax.', description:'Choose the Hero controlling the fewest Monsters. That hero places a new Monster on any tile with an unexplored edge'},
        {id: 30, evt_type: 0, name: 'Cyrus belview', flavour: 'A gaunt, ghoulish looking man in a torn suit grins at you through yellowed teeth. "The master said we were expecting company. Allow me to escort you to your chambers."', description:'Draw a tile from the bottom of the Dungeon Tile stack and place it adjacent to any unexplored edge. Place two new Monster on that tile then place the active Hero on that tile. Each other Hero can place themselves on the active Hero\'s new tile.'},
        {id: 31, evt_type: 1, name: 'Green slime', flavour: 'A hideous blob of green slime falls from the ceiling', description:'Attack each Hero on the active hero\'s tile\nIf the active Hero is hit by the attack, the active Hero discards 1 treasure Card at random'},
        {id: 32, evt_type: 1, name: 'Circle of death', flavour: 'A wave of shadows pulse stopping energy blossoms from the center of the room.', description:'Attack each Hero on the active Hero\'s tile.\nEach Undead Monster on the active Hero\'s tile regains 1 Hit Point'},
        {id: 33, evt_type: 1, name: 'Hand\'s of the dead', flavour: 'Severed hands crawl from the earth and grab at you.', description:'Attack each Hero on the active Hero\'s tile.\nIf a Hero is hit by the attack, the Hero is slowed'},
        {id: 34, evt_type: 1, name: 'Spider webs', flavour: 'Hundreds of tiny spiders crawl across the ceiling, sending a thick mass of webs down upon you.', description:'Attack the active Hero'},
        {id: 35, evt_type: 1, name: 'Howling ghost', flavour: 'A shrieking emerges from the shadows; its howl causes you to recoil in agony', description:'Attack each Hero on the active Hero\'s tile. A Hero hit by this attack can flip an unused Daily power over ot prevent this damage'},
        {id: 36, evt_type: 1, name: 'Patrina velikovna', flavour: 'The ghostly image of an elf maid appears before you. She smiles for a moment before unleashing a blood curdling shriek.', description:'Attack each Hero.\nAfter the attack, place each Monster that is not on the same tile as a Hero 1 tile closer to the closest Hero'},
        {id: 37, evt_type: 1, name: 'Icy corridor', flavour: 'A thin layer of ice makes it difficult to stand in one place', description:'Attack each Hero on the active Hero\'s tile.\nAfter the attack, place each Hero on the active Hero\'s tile on a tile within 1 tile of the active Hero\'s tile. (Heroes can be placed on different tiles.)'},
        {id: 38, evt_type: 1, name: 'Animated armor', flavour: 'Suits of armor spring out of dark alcoves to attack you', description:'Attack each Hero on the active Hero\'s tile.'},
        {id: 39, evt_type: 1, name: 'Gray ooze', flavour: 'A pseudopod emerges from a puddle of gray ooze on the ground and strikes at you.', description:'Attack the active Hero\nIf the active Hero is hit by the attack, the active Hero discards 1 Treasure Card at random'},
        {id: 40, evt_type: 1, name: 'Strahd attacks!', flavour: 'Strahd steps from the shadows, sending a ball of fire streaking from his outstretched hands. As it explodes, he disappears back into the shadows.', description:'Attack each Hero within 1 tile of the active Hero'},
        {id: 41, evt_type: 1, name: 'King Tomescu\'s portal', flavour: 'You fall through a mysterious portal, reappearing elsewhere in the crypts covered with wounds.', description:'Attack the active Hero three times.\nRemove the active Hero from his or her tile. At this start of that Hero\'s next Hero Phase, place that Hero on any tile.'},
        {id: 42, evt_type: 1, name: 'Choking fog', flavour: 'Acrid, yellow smoke fills the crypt, causing you to choke and cough', description:'Attack each Hero on the active Hero\'s tile'},
        {id: 43, evt_type: 1, name: 'Prowling Ghost', flavour: 'The ghosts of past adventurers haunt this room. Their shrieks send you running deeper in to the dungeon.', description:'Attack the active Hero.\nAfter the attack, draw a tile from the bottom of the Dungeon Tile stack and place it adjacent to the unexplored edge that is closest to the active Hero. Place a new Monster on that tile, and then place the active Hero on that tile.'},
        {id: 44, evt_type: 1, name: 'Ambush!', flavour: 'A massive net falls from the ceiling while monsters close in from all sides.', description:'Attack each Hero o the active Hero\'s tile.'},
        {id: 45, evt_type: 1, name: 'Ambush!', flavour: 'A massive net falls from the ceiling while monsters close in from all sides.', description:'Attack each Hero o the active Hero\'s tile.'},
        {id: 46, evt_type: 2, name: 'Bat swarm', flavour: 'A horde of shrieking bats flutter through th catacombs, blocking your sight', description:'Whenever a Hero attacks a Monster that is not on his or her tile, that Hero makes the attack roll twice, and uses the lower result'},
        {id: 47, evt_type: 2, name: 'Cackling skull', flavour: 'A crystal skull floats out of the darkness. Its maddening laughter makes it difficult to focus.', description:'Whenever a Hero uses a Daily power or Utility power, that Hero takes 1 damage'},
        {id: 48, evt_type: 2, name: 'Deadly shadows', flavour: 'Voices from the shadows whisper horrifying secrets about your companions', description:'Whenever the active Hero ends his or her turn on a tile that has another Hero on it, the active Hero takes 1 damage'},
        {id: 49, evt_type: 2, name: 'Crippling miasma', flavour: 'A horrible stench of decay fills the air.', description:'Each Hero\'s speed is reduce d by 1.\n\n(Slowed Heroes are unaffected.)'},
        {id: 50, evt_type: 2, name: 'Spirit of doom', flavour: 'A grim specter materialises nearby, bringing portents of impending doom.', description:'Whenever a Hero discards a Treasure card, they take 1 damage'},
        {id: 51, evt_type: 2, name: 'Haunted mists', flavour: 'You catch glimpses of the faces of long dead adventurers in the mists that fill the crypt', description:'Undead Monsters gain a +2 bonus to to attack rolls.'},
        {id: 52, evt_type: 2, name: 'Blood fog', flavour: 'A mystical reddish fog brings out the inner animal in the living and the dead', description:'Whenever a Hero or a Monster attack and rolls a natural 17 or higher, the target of the attack takes 1 additional damage'},
        {id: 53, evt_type: 2, name: 'Music of the damned', flavour: 'The haunting sound of an organ echoes through the crypts, sending shivers down your spine.', description:'Whenever a Hero would place a new Monster, that Hero draws two Monster Cards and chooses the Monster worth the most experience. He or she places that Monster and discards the other.'},
        {id: 54, evt_type: 3, name: 'Sliding walls', flavour: 'You hear the grinding of stone against stone as the walls separate you from your allies.', description:'Trigger the Trap during your Villain Phase: Roll the die for each Hero on this tile and place that Hero on a tile within 1 tile of this Trap in the direction indicated by the Sliding Walls marker. If the direction rolled is a wall or an unexplored tile, the Hero takes 1 damage and remains on this tile.'},
        {id: 55, evt_type: 3, name: 'Alarm', flavour: 'The distant clatter of bells echos through the crypts, drawing monster out of their lairs to attack!', description:'Trigger the trap during your Villain Phase: Place a new Monster o the unexplored edge that is closest to the Alarm marker'},
        {id: 56, evt_type: 3, name: 'Crushing walls', flavour: 'The walls slide toward each other, trapping you between them!', description:'Trigger the Trap during your Villain Phase: Attack each Hero on this tile.'},
        {id: 57, evt_type: 3, name: 'Crossbow turret', flavour: 'A pair of armored crossbow turrets emerges from the wall to pepper you with quarrels!', description:'Trigger the Trap during your Villain Phase: Attack each Hero  within 1 tile of this Trap'},
        {id: 58, evt_type: 3, name: 'Dart trap', flavour: 'A soft click of a pressure plate beneath your feet precedes the volley of darts that explode from the wall', description:'Trigger the Trap during your Villain Phase: Attack each Hero on this tile'},
        {id: 59, evt_type: 3, name: 'Spear gauntlet', flavour: 'Spears pop out of the ground, skewering you!', description:'Trigger the Trap during your Villain Phase: Attack each Hero within 1 tile of this trap'},
        {id: 60, evt_type: 3, name: 'Fire trap', flavour: 'Jets of fire erupt from the walls and ceiling to engulf you.', description:'Trigger the Trap during your Villain Phase: Each Hero on this tile take 2 damage'},
    
      ]);
    });
};
